// All Classical Latin reference data

const PERSONS = ['1st sg', '2nd sg', '3rd sg', '1st pl', '2nd pl', '3rd pl'];
const CASES = ['Nominative', 'Genitive', 'Dative', 'Accusative', 'Ablative', 'Vocative'];

// ─── VERBS ────────────────────────────────────────────────────────────────────

const VERB_DATA = {
  first: {
    name: '1st Conjugation (-āre)',
    lemma: 'amō, amāre, amāvī, amātum',
    meaning: 'to love',
    indicative: {
      presentActive:     { name:'Present Active',         forms:['amō','amās','amat','amāmus','amātis','amant'],                     endings:['-ō','-ās','-at','-āmus','-ātis','-ant'] },
      imperfectActive:   { name:'Imperfect Active',       forms:['amābam','amābās','amābat','amābāmus','amābātis','amābant'],         endings:['-bam','-bās','-bat','-bāmus','-bātis','-bant'] },
      futureActive:      { name:'Future Active',          forms:['amābō','amābis','amābit','amābimus','amābitis','amābunt'],          endings:['-bō','-bis','-bit','-bimus','-bitis','-bunt'] },
      perfectActive:     { name:'Perfect Active',         forms:['amāvī','amāvistī','amāvit','amāvimus','amāvistis','amāvērunt'],    endings:['-ī','-istī','-it','-imus','-istis','-ērunt'] },
      pluperfectActive:  { name:'Pluperfect Active',      forms:['amāveram','amāverās','amāverat','amāverāmus','amāverātis','amāverant'], endings:['-eram','-erās','-erat','-erāmus','-erātis','-erant'] },
      futperfActive:     { name:'Future Perfect Active',  forms:['amāverō','amāveris','amāverit','amāverimus','amāveritis','amāverint'], endings:['-erō','-eris','-erit','-erimus','-eritis','-erint'] },
      presentPassive:    { name:'Present Passive',        forms:['amor','amāris','amātur','amāmur','amāminī','amantur'],             endings:['-or','-āris','-ātur','-āmur','-āminī','-antur'] },
      imperfectPassive:  { name:'Imperfect Passive',      forms:['amābar','amābāris','amābātur','amābāmur','amābāminī','amābantur'], endings:['-bar','-bāris','-bātur','-bāmur','-bāminī','-bantur'] },
      futurePassive:     { name:'Future Passive',         forms:['amābor','amāberis','amābitur','amābimur','amābiminī','amābuntur'], endings:['-bor','-beris','-bitur','-bimur','-biminī','-buntur'] },
      perfectPassive:    { name:'Perfect Passive',        forms:['amātus sum','amātus es','amātus est','amātī sumus','amātī estis','amātī sunt'], endings:['PPP + sum','PPP + es','PPP + est','PPP + sumus','PPP + estis','PPP + sunt'] },
      pluperfectPassive: { name:'Pluperfect Passive',     forms:['amātus eram','amātus erās','amātus erat','amātī erāmus','amātī erātis','amātī erant'], endings:['PPP + eram','PPP + erās','PPP + erat','PPP + erāmus','PPP + erātis','PPP + erant'] },
      futperfPassive:    { name:'Future Perfect Passive',  forms:['amātus erō','amātus eris','amātus erit','amātī erimus','amātī eritis','amātī erunt'], endings:['PPP + erō','PPP + eris','PPP + erit','PPP + erimus','PPP + eritis','PPP + erunt'] },
    },
    subjunctive: {
      presentActive:    { name:'Present Active',          forms:['amem','amēs','amet','amēmus','amētis','ament'],                   endings:['-em','-ēs','-et','-ēmus','-ētis','-ent'], note:'ā → ē' },
      imperfectActive:  { name:'Imperfect Active',        forms:['amārem','amārēs','amāret','amārēmus','amārētis','amārent'],       endings:['-rem','-rēs','-ret','-rēmus','-rētis','-rent'], note:'Infinitive + endings' },
      perfectActive:    { name:'Perfect Active',          forms:['amāverim','amāverīs','amāverit','amāverīmus','amāverītis','amāverint'], endings:['-erim','-erīs','-erit','-erīmus','-erītis','-erint'] },
      pluperfectActive: { name:'Pluperfect Active',       forms:['amāvissem','amāvissēs','amāvisset','amāvissēmus','amāvissētis','amāvissent'], endings:['-issem','-issēs','-isset','-issēmus','-issētis','-issent'] },
      presentPassive:   { name:'Present Passive',         forms:['amer','amēris','amētur','amēmur','amēminī','amentur'],            endings:['-er','-ēris','-ētur','-ēmur','-ēminī','-entur'] },
      imperfectPassive: { name:'Imperfect Passive',       forms:['amārer','amārēris','amārētur','amārēmur','amārēminī','amārentur'], endings:['-rer','-rēris','-rētur','-rēmur','-rēminī','-rentur'] },
    },
    imperative: {
      active:  { singular:'amā', plural:'amāte' },
      passive: { singular:'amāre', plural:'amāminī' },
    },
    infinitives: [
      { label:'Present Active',   form:'amāre' },
      { label:'Perfect Active',   form:'amāvisse' },
      { label:'Future Active',    form:'amātūrum esse' },
      { label:'Present Passive',  form:'amārī' },
      { label:'Perfect Passive',  form:'amātum esse' },
      { label:'Future Passive',   form:'amātum īrī' },
    ],
    participles: [
      { label:'Present Active (pres. act. part.)',   form:'amāns, amantis' },
      { label:'Perfect Passive (PPP)',               form:'amātus, -a, -um' },
      { label:'Future Active',                       form:'amātūrus, -a, -um' },
      { label:'Gerundive (fut. pass.)',              form:'amandus, -a, -um' },
    ],
    gerund: { gen:'amandī', dat:'amandō', acc:'amandum', abl:'amandō' },
  },

  second: {
    name: '2nd Conjugation (-ēre)',
    lemma: 'moneō, monēre, monuī, monitum',
    meaning: 'to warn, advise',
    indicative: {
      presentActive:     { name:'Present Active',         forms:['moneō','monēs','monet','monēmus','monētis','monent'],                 endings:['-eō','-ēs','-et','-ēmus','-ētis','-ent'] },
      imperfectActive:   { name:'Imperfect Active',       forms:['monēbam','monēbās','monēbat','monēbāmus','monēbātis','monēbant'],     endings:['-bam','-bās','-bat','-bāmus','-bātis','-bant'] },
      futureActive:      { name:'Future Active',          forms:['monēbō','monēbis','monēbit','monēbimus','monēbitis','monēbunt'],      endings:['-bō','-bis','-bit','-bimus','-bitis','-bunt'] },
      perfectActive:     { name:'Perfect Active',         forms:['monuī','monuistī','monuit','monuimus','monuistis','monuērunt'],       endings:['-ī','-istī','-it','-imus','-istis','-ērunt'] },
      pluperfectActive:  { name:'Pluperfect Active',      forms:['monueram','monuerās','monuerat','monuerāmus','monuerātis','monuerant'], endings:['-eram','-erās','-erat','-erāmus','-erātis','-erant'] },
      futperfActive:     { name:'Future Perfect Active',  forms:['monuerō','monueris','monuerit','monuerimus','monueritis','monuerint'], endings:['-erō','-eris','-erit','-erimus','-eritis','-erint'] },
      presentPassive:    { name:'Present Passive',        forms:['moneor','monēris','monētur','monēmur','monēminī','monentur'],         endings:['-eor','-ēris','-ētur','-ēmur','-ēminī','-entur'] },
      imperfectPassive:  { name:'Imperfect Passive',      forms:['monēbar','monēbāris','monēbātur','monēbāmur','monēbāminī','monēbantur'], endings:['-bar','-bāris','-bātur','-bāmur','-bāminī','-bantur'] },
      futurePassive:     { name:'Future Passive',         forms:['monēbor','monēberis','monēbitur','monēbimur','monēbiminī','monēbuntur'], endings:['-bor','-beris','-bitur','-bimur','-biminī','-buntur'] },
      perfectPassive:    { name:'Perfect Passive',        forms:['monitus sum','monitus es','monitus est','monitī sumus','monitī estis','monitī sunt'], endings:['PPP + sum','PPP + es','PPP + est','PPP + sumus','PPP + estis','PPP + sunt'] },
      pluperfectPassive: { name:'Pluperfect Passive',     forms:['monitus eram','monitus erās','monitus erat','monitī erāmus','monitī erātis','monitī erant'], endings:['PPP + eram','-','-','-','-','-'] },
      futperfPassive:    { name:'Future Perfect Passive',  forms:['monitus erō','monitus eris','monitus erit','monitī erimus','monitī eritis','monitī erunt'], endings:['PPP + erō','-','-','-','-','-'] },
    },
    subjunctive: {
      presentActive:    { name:'Present Active',          forms:['moneam','moneās','moneat','moneāmus','moneātis','moneant'],           endings:['-eam','-eās','-eat','-eāmus','-eātis','-eant'], note:'ē → eā' },
      imperfectActive:  { name:'Imperfect Active',        forms:['monērem','monērēs','monēret','monērēmus','monērētis','monērent'],     endings:['-rem','-rēs','-ret','-rēmus','-rētis','-rent'] },
      perfectActive:    { name:'Perfect Active',          forms:['monuerim','monuerīs','monuerit','monuerīmus','monuerītis','monuerint'], endings:['-erim','-erīs','-erit','-erīmus','-erītis','-erint'] },
      pluperfectActive: { name:'Pluperfect Active',       forms:['monuissem','monuissēs','monuisset','monuissēmus','monuissētis','monuissent'], endings:['-issem','-issēs','-isset','-issēmus','-issētis','-issent'] },
      presentPassive:   { name:'Present Passive',         forms:['monear','moneāris','moneātur','moneāmur','moneāminī','moneantur'],   endings:['-ear','-eāris','-eātur','-eāmur','-eāminī','-eantur'] },
      imperfectPassive: { name:'Imperfect Passive',       forms:['monērer','monērēris','monērētur','monērēmur','monērēminī','monērentur'], endings:['-rer','-rēris','-rētur','-rēmur','-rēminī','-rentur'] },
    },
    imperative: {
      active:  { singular:'monē', plural:'monēte' },
      passive: { singular:'monēre', plural:'monēminī' },
    },
    infinitives: [
      { label:'Present Active',   form:'monēre' },
      { label:'Perfect Active',   form:'monuisse' },
      { label:'Future Active',    form:'monitūrum esse' },
      { label:'Present Passive',  form:'monērī' },
      { label:'Perfect Passive',  form:'monitum esse' },
      { label:'Future Passive',   form:'monitum īrī' },
    ],
    participles: [
      { label:'Present Active',  form:'monēns, monentis' },
      { label:'Perfect Passive', form:'monitus, -a, -um' },
      { label:'Future Active',   form:'monitūrus, -a, -um' },
      { label:'Gerundive',       form:'monendus, -a, -um' },
    ],
    gerund: { gen:'monendī', dat:'monendō', acc:'monendum', abl:'monendō' },
  },

  third: {
    name: '3rd Conjugation (-ere)',
    lemma: 'dūcō, dūcere, dūxī, ductum',
    meaning: 'to lead',
    indicative: {
      presentActive:     { name:'Present Active',         forms:['dūcō','dūcis','dūcit','dūcimus','dūcitis','dūcunt'],                 endings:['-ō','-is','-it','-imus','-itis','-unt'] },
      imperfectActive:   { name:'Imperfect Active',       forms:['dūcēbam','dūcēbās','dūcēbat','dūcēbāmus','dūcēbātis','dūcēbant'],   endings:['-ēbam','-ēbās','-ēbat','-ēbāmus','-ēbātis','-ēbant'] },
      futureActive:      { name:'Future Active',          forms:['dūcam','dūcēs','dūcet','dūcēmus','dūcētis','dūcent'],               endings:['-am','-ēs','-et','-ēmus','-ētis','-ent'] },
      perfectActive:     { name:'Perfect Active',         forms:['dūxī','dūxistī','dūxit','dūximus','dūxistis','dūxērunt'],           endings:['-ī','-istī','-it','-imus','-istis','-ērunt'] },
      pluperfectActive:  { name:'Pluperfect Active',      forms:['dūxeram','dūxerās','dūxerat','dūxerāmus','dūxerātis','dūxerant'],   endings:['-eram','-erās','-erat','-erāmus','-erātis','-erant'] },
      futperfActive:     { name:'Future Perfect Active',  forms:['dūxerō','dūxeris','dūxerit','dūxerimus','dūxeritis','dūxerint'],   endings:['-erō','-eris','-erit','-erimus','-eritis','-erint'] },
      presentPassive:    { name:'Present Passive',        forms:['dūcor','dūceris','dūcitur','dūcimur','dūciminī','dūcuntur'],         endings:['-or','-eris','-itur','-imur','-iminī','-untur'] },
      imperfectPassive:  { name:'Imperfect Passive',      forms:['dūcēbar','dūcēbāris','dūcēbātur','dūcēbāmur','dūcēbāminī','dūcēbantur'], endings:['-ēbar','-ēbāris','-ēbātur','-ēbāmur','-ēbāminī','-ēbantur'] },
      futurePassive:     { name:'Future Passive',         forms:['dūcar','dūcēris','dūcētur','dūcēmur','dūcēminī','dūcentur'],        endings:['-ar','-ēris','-ētur','-ēmur','-ēminī','-entur'] },
      perfectPassive:    { name:'Perfect Passive',        forms:['ductus sum','ductus es','ductus est','ductī sumus','ductī estis','ductī sunt'], endings:['PPP + sum','-','-','-','-','-'] },
      pluperfectPassive: { name:'Pluperfect Passive',     forms:['ductus eram','ductus erās','ductus erat','ductī erāmus','ductī erātis','ductī erant'], endings:['PPP + eram','-','-','-','-','-'] },
      futperfPassive:    { name:'Future Perfect Passive',  forms:['ductus erō','ductus eris','ductus erit','ductī erimus','ductī eritis','ductī erunt'], endings:['PPP + erō','-','-','-','-','-'] },
    },
    subjunctive: {
      presentActive:    { name:'Present Active',          forms:['dūcam','dūcās','dūcat','dūcāmus','dūcātis','dūcant'],               endings:['-am','-ās','-at','-āmus','-ātis','-ant'], note:'stem vowel → ā' },
      imperfectActive:  { name:'Imperfect Active',        forms:['dūcerem','dūcerēs','dūceret','dūcerēmus','dūcerētis','dūcerent'],   endings:['-erem','-erēs','-eret','-erēmus','-erētis','-erent'] },
      perfectActive:    { name:'Perfect Active',          forms:['dūxerim','dūxerīs','dūxerit','dūxerīmus','dūxerītis','dūxerint'],  endings:['-erim','-erīs','-erit','-erīmus','-erītis','-erint'] },
      pluperfectActive: { name:'Pluperfect Active',       forms:['dūxissem','dūxissēs','dūxisset','dūxissēmus','dūxissētis','dūxissent'], endings:['-issem','-issēs','-isset','-issēmus','-issētis','-issent'] },
      presentPassive:   { name:'Present Passive',         forms:['dūcar','dūcāris','dūcātur','dūcāmur','dūcāminī','dūcantur'],        endings:['-ar','-āris','-ātur','-āmur','-āminī','-antur'] },
      imperfectPassive: { name:'Imperfect Passive',       forms:['dūcerer','dūcerēris','dūcerētur','dūcerēmur','dūcerēminī','dūcerentur'], endings:['-erer','-erēris','-erētur','-erēmur','-erēminī','-erentur'] },
    },
    imperative: {
      active:  { singular:'dūc', plural:'dūcite', note:'Short form (cf. dīc, fac, fer)' },
      passive: { singular:'dūcere', plural:'dūciminī' },
    },
    infinitives: [
      { label:'Present Active',   form:'dūcere' },
      { label:'Perfect Active',   form:'dūxisse' },
      { label:'Future Active',    form:'ductūrum esse' },
      { label:'Present Passive',  form:'dūcī' },
      { label:'Perfect Passive',  form:'ductum esse' },
      { label:'Future Passive',   form:'ductum īrī' },
    ],
    participles: [
      { label:'Present Active',  form:'dūcēns, ducentis' },
      { label:'Perfect Passive', form:'ductus, -a, -um' },
      { label:'Future Active',   form:'ductūrus, -a, -um' },
      { label:'Gerundive',       form:'dūcendus, -a, -um' },
    ],
    gerund: { gen:'dūcendī', dat:'dūcendō', acc:'dūcendum', abl:'dūcendō' },
  },

  thirdio: {
    name: '3rd-iō Conjugation (-ere)',
    lemma: 'capiō, capere, cēpī, captum',
    meaning: 'to take, capture',
    indicative: {
      presentActive:     { name:'Present Active',         forms:['capiō','capis','capit','capimus','capitis','capiunt'],               endings:['-iō','-is','-it','-imus','-itis','-iunt'] },
      imperfectActive:   { name:'Imperfect Active',       forms:['capiēbam','capiēbās','capiēbat','capiēbāmus','capiēbātis','capiēbant'], endings:['-iēbam','-iēbās','-iēbat','-iēbāmus','-iēbātis','-iēbant'] },
      futureActive:      { name:'Future Active',          forms:['capiam','capiēs','capiet','capiēmus','capiētis','capient'],          endings:['-iam','-iēs','-iet','-iēmus','-iētis','-ient'] },
      perfectActive:     { name:'Perfect Active',         forms:['cēpī','cēpistī','cēpit','cēpimus','cēpistis','cēpērunt'],           endings:['-ī','-istī','-it','-imus','-istis','-ērunt'] },
      pluperfectActive:  { name:'Pluperfect Active',      forms:['cēperam','cēperās','cēperat','cēperāmus','cēperātis','cēperant'],   endings:['-eram','-erās','-erat','-erāmus','-erātis','-erant'] },
      futperfActive:     { name:'Future Perfect Active',  forms:['cēperō','cēperis','cēperit','cēperimus','cēperitis','cēperint'],   endings:['-erō','-eris','-erit','-erimus','-eritis','-erint'] },
      presentPassive:    { name:'Present Passive',        forms:['capior','caperis','capitur','capimur','capiminī','capiuntur'],       endings:['-ior','-eris','-itur','-imur','-iminī','-iuntur'] },
      imperfectPassive:  { name:'Imperfect Passive',      forms:['capiēbar','capiēbāris','capiēbātur','capiēbāmur','capiēbāminī','capiēbantur'], endings:['-iēbar','-iēbāris','-iēbātur','-iēbāmur','-iēbāminī','-iēbantur'] },
      futurePassive:     { name:'Future Passive',         forms:['capiar','capiēris','capiētur','capiēmur','capiēminī','capientur'],   endings:['-iar','-iēris','-iētur','-iēmur','-iēminī','-ientur'] },
      perfectPassive:    { name:'Perfect Passive',        forms:['captus sum','captus es','captus est','captī sumus','captī estis','captī sunt'], endings:['PPP + sum','-','-','-','-','-'] },
      pluperfectPassive: { name:'Pluperfect Passive',     forms:['captus eram','captus erās','captus erat','captī erāmus','captī erātis','captī erant'], endings:['PPP + eram','-','-','-','-','-'] },
      futperfPassive:    { name:'Future Perfect Passive',  forms:['captus erō','captus eris','captus erit','captī erimus','captī eritis','captī erunt'], endings:['PPP + erō','-','-','-','-','-'] },
    },
    subjunctive: {
      presentActive:    { name:'Present Active',          forms:['capiam','capiās','capiat','capiāmus','capiātis','capiant'],         endings:['-iam','-iās','-iat','-iāmus','-iātis','-iant'] },
      imperfectActive:  { name:'Imperfect Active',        forms:['caperem','caperēs','caperet','caperēmus','caperētis','caperent'],   endings:['-erem','-erēs','-eret','-erēmus','-erētis','-erent'] },
      perfectActive:    { name:'Perfect Active',          forms:['cēperim','cēperīs','cēperit','cēperīmus','cēperītis','cēperint'],  endings:['-erim','-erīs','-erit','-erīmus','-erītis','-erint'] },
      pluperfectActive: { name:'Pluperfect Active',       forms:['cēpissem','cēpissēs','cēpisset','cēpissēmus','cēpissētis','cēpissent'], endings:['-issem','-issēs','-isset','-issēmus','-issētis','-issent'] },
      presentPassive:   { name:'Present Passive',         forms:['capiar','capiāris','capiātur','capiāmur','capiāminī','capiantur'], endings:['-iar','-iāris','-iātur','-iāmur','-iāminī','-iantur'] },
      imperfectPassive: { name:'Imperfect Passive',       forms:['caperer','caperēris','caperētur','caperēmur','caperēminī','caperentur'], endings:['-erer','-erēris','-erētur','-erēmur','-erēminī','-erentur'] },
    },
    imperative: {
      active:  { singular:'cape', plural:'capite' },
      passive: { singular:'capere', plural:'capiminī' },
    },
    infinitives: [
      { label:'Present Active',   form:'capere' },
      { label:'Perfect Active',   form:'cēpisse' },
      { label:'Future Active',    form:'captūrum esse' },
      { label:'Present Passive',  form:'capī' },
      { label:'Perfect Passive',  form:'captum esse' },
      { label:'Future Passive',   form:'captum īrī' },
    ],
    participles: [
      { label:'Present Active',  form:'capiēns, capientis' },
      { label:'Perfect Passive', form:'captus, -a, -um' },
      { label:'Future Active',   form:'captūrus, -a, -um' },
      { label:'Gerundive',       form:'capiendus, -a, -um' },
    ],
    gerund: { gen:'capiendī', dat:'capiendō', acc:'capiendum', abl:'capiendō' },
  },

  fourth: {
    name: '4th Conjugation (-īre)',
    lemma: 'audiō, audīre, audīvī, audītum',
    meaning: 'to hear, listen to',
    indicative: {
      presentActive:     { name:'Present Active',         forms:['audiō','audīs','audit','audīmus','audītis','audiunt'],               endings:['-iō','-īs','-it','-īmus','-ītis','-iunt'] },
      imperfectActive:   { name:'Imperfect Active',       forms:['audiēbam','audiēbās','audiēbat','audiēbāmus','audiēbātis','audiēbant'], endings:['-iēbam','-iēbās','-iēbat','-iēbāmus','-iēbātis','-iēbant'] },
      futureActive:      { name:'Future Active',          forms:['audiam','audiēs','audiet','audiēmus','audiētis','audient'],          endings:['-iam','-iēs','-iet','-iēmus','-iētis','-ient'] },
      perfectActive:     { name:'Perfect Active',         forms:['audīvī','audīvistī','audīvit','audīvimus','audīvistis','audīvērunt'], endings:['-ī','-istī','-it','-imus','-istis','-ērunt'] },
      pluperfectActive:  { name:'Pluperfect Active',      forms:['audīveram','audīverās','audīverat','audīverāmus','audīverātis','audīverant'], endings:['-eram','-erās','-erat','-erāmus','-erātis','-erant'] },
      futperfActive:     { name:'Future Perfect Active',  forms:['audīverō','audīveris','audīverit','audīverimus','audīveritis','audīverint'], endings:['-erō','-eris','-erit','-erimus','-eritis','-erint'] },
      presentPassive:    { name:'Present Passive',        forms:['audior','audīris','audītur','audīmur','audīminī','audiuntur'],       endings:['-ior','-īris','-ītur','-īmur','-īminī','-iuntur'] },
      imperfectPassive:  { name:'Imperfect Passive',      forms:['audiēbar','audiēbāris','audiēbātur','audiēbāmur','audiēbāminī','audiēbantur'], endings:['-iēbar','-iēbāris','-iēbātur','-iēbāmur','-iēbāminī','-iēbantur'] },
      futurePassive:     { name:'Future Passive',         forms:['audiar','audiēris','audiētur','audiēmur','audiēminī','audientur'],   endings:['-iar','-iēris','-iētur','-iēmur','-iēminī','-ientur'] },
      perfectPassive:    { name:'Perfect Passive',        forms:['audītus sum','audītus es','audītus est','audītī sumus','audītī estis','audītī sunt'], endings:['PPP + sum','-','-','-','-','-'] },
      pluperfectPassive: { name:'Pluperfect Passive',     forms:['audītus eram','audītus erās','audītus erat','audītī erāmus','audītī erātis','audītī erant'], endings:['PPP + eram','-','-','-','-','-'] },
      futperfPassive:    { name:'Future Perfect Passive',  forms:['audītus erō','audītus eris','audītus erit','audītī erimus','audītī eritis','audītī erunt'], endings:['PPP + erō','-','-','-','-','-'] },
    },
    subjunctive: {
      presentActive:    { name:'Present Active',          forms:['audiam','audiās','audiat','audiāmus','audiātis','audiant'],         endings:['-iam','-iās','-iat','-iāmus','-iātis','-iant'] },
      imperfectActive:  { name:'Imperfect Active',        forms:['audīrem','audīrēs','audīret','audīrēmus','audīrētis','audīrent'],  endings:['-rem','-rēs','-ret','-rēmus','-rētis','-rent'] },
      perfectActive:    { name:'Perfect Active',          forms:['audīverim','audīverīs','audīverit','audīverīmus','audīverītis','audīverint'], endings:['-erim','-erīs','-erit','-erīmus','-erītis','-erint'] },
      pluperfectActive: { name:'Pluperfect Active',       forms:['audīvissem','audīvissēs','audīvisset','audīvissēmus','audīvissētis','audīvissent'], endings:['-issem','-issēs','-isset','-issēmus','-issētis','-issent'] },
      presentPassive:   { name:'Present Passive',         forms:['audiar','audiāris','audiātur','audiāmur','audiāminī','audiantur'],  endings:['-iar','-iāris','-iātur','-iāmur','-iāminī','-iantur'] },
      imperfectPassive: { name:'Imperfect Passive',       forms:['audīrer','audīrēris','audīrētur','audīrēmur','audīrēminī','audīrentur'], endings:['-rer','-rēris','-rētur','-rēmur','-rēminī','-rentur'] },
    },
    imperative: {
      active:  { singular:'audī', plural:'audīte' },
      passive: { singular:'audīre', plural:'audīminī' },
    },
    infinitives: [
      { label:'Present Active',   form:'audīre' },
      { label:'Perfect Active',   form:'audīvisse' },
      { label:'Future Active',    form:'audītūrum esse' },
      { label:'Present Passive',  form:'audīrī' },
      { label:'Perfect Passive',  form:'audītum esse' },
      { label:'Future Passive',   form:'audītum īrī' },
    ],
    participles: [
      { label:'Present Active',  form:'audiēns, audientis' },
      { label:'Perfect Passive', form:'audītus, -a, -um' },
      { label:'Future Active',   form:'audītūrus, -a, -um' },
      { label:'Gerundive',       form:'audiendus, -a, -um' },
    ],
    gerund: { gen:'audiendī', dat:'audiendō', acc:'audiendum', abl:'audiendō' },
  },

  esse: {
    name: 'Irregular: esse (to be)',
    lemma: 'sum, esse, fuī, futūrum',
    meaning: 'to be',
    indicative: {
      presentActive:     { name:'Present',         forms:['sum','es','est','sumus','estis','sunt'],                               endings:['sum','es','est','sumus','estis','sunt'] },
      imperfectActive:   { name:'Imperfect',       forms:['eram','erās','erat','erāmus','erātis','erant'],                       endings:['-eram','-erās','-erat','-erāmus','-erātis','-erant'] },
      futureActive:      { name:'Future',          forms:['erō','eris','erit','erimus','eritis','erunt'],                        endings:['-erō','-eris','-erit','-erimus','-eritis','-erunt'] },
      perfectActive:     { name:'Perfect',         forms:['fuī','fuistī','fuit','fuimus','fuistis','fuērunt'],                   endings:['-fuī','-fuistī','-fuit','-fuimus','-fuistis','-fuērunt'] },
      pluperfectActive:  { name:'Pluperfect',      forms:['fueram','fuerās','fuerat','fuerāmus','fuerātis','fuerant'],           endings:['-fueram','-fuerās','-fuerat','-fuerāmus','-fuerātis','-fuerant'] },
      futperfActive:     { name:'Future Perfect',  forms:['fuerō','fueris','fuerit','fuerimus','fueritis','fuerint'],            endings:['-fuerō','-fueris','-fuerit','-fuerimus','-fueritis','-fuerint'] },
    },
    subjunctive: {
      presentActive:    { name:'Present',          forms:['sim','sīs','sit','sīmus','sītis','sint'],                             endings:['sim','sīs','sit','sīmus','sītis','sint'] },
      imperfectActive:  { name:'Imperfect',        forms:['essem','essēs','esset','essēmus','essētis','essent'],                 endings:['essem','essēs','esset','essēmus','essētis','essent'] },
      perfectActive:    { name:'Perfect',          forms:['fuerim','fuerīs','fuerit','fuerīmus','fuerītis','fuerint'],           endings:['-fuerim','-fuerīs','-fuerit','-fuerīmus','-fuerītis','-fuerint'] },
      pluperfectActive: { name:'Pluperfect',       forms:['fuissem','fuissēs','fuisset','fuissēmus','fuissētis','fuissent'],    endings:['fuissem','-','-','-','-','-'] },
    },
    imperative: { active: { singular:'es', plural:'este' } },
    infinitives: [
      { label:'Present',  form:'esse' },
      { label:'Perfect',  form:'fuisse' },
      { label:'Future',   form:'futūrum esse (fore)' },
    ],
    participles: [
      { label:'Future Active', form:'futūrus, -a, -um' },
    ],
    note: 'esse has no passive forms (it is a linking verb)',
  },

  ire: {
    name: 'Irregular: īre (to go)',
    lemma: 'eō, īre, iī / īvī, itum',
    meaning: 'to go',
    indicative: {
      presentActive:     { name:'Present',         forms:['eō','īs','it','īmus','ītis','eunt'],                                  endings:['eō','īs','it','īmus','ītis','eunt'] },
      imperfectActive:   { name:'Imperfect',       forms:['ībam','ībās','ībat','ībāmus','ībātis','ībant'],                      endings:['ībam','-','-','-','-','-'] },
      futureActive:      { name:'Future',          forms:['ībō','ībis','ībit','ībimus','ībitis','ībunt'],                       endings:['ībō','-','-','-','-','-'] },
      perfectActive:     { name:'Perfect',         forms:['iī (īvī)','iistī (īvistī)','iit (īvit)','iimus (īvimus)','iistis (īvistis)','iērunt (īvērunt)'], endings:['iī','-','-','-','-','-'] },
      pluperfectActive:  { name:'Pluperfect',      forms:['ieram','ierās','ierat','ierāmus','ierātis','ierant'],                endings:['ieram','-','-','-','-','-'] },
      futperfActive:     { name:'Future Perfect',  forms:['ierō','ieris','ierit','ierimus','ieritis','ierint'],                 endings:['ierō','-','-','-','-','-'] },
    },
    subjunctive: {
      presentActive:    { name:'Present',          forms:['eam','eās','eat','eāmus','eātis','eant'],                            endings:['eam','-','-','-','-','-'] },
      imperfectActive:  { name:'Imperfect',        forms:['īrem','īrēs','īret','īrēmus','īrētis','īrent'],                     endings:['īrem','-','-','-','-','-'] },
      perfectActive:    { name:'Perfect',          forms:['ierim','ierīs','ierit','ierīmus','ierītis','ierint'],                endings:['ierim','-','-','-','-','-'] },
      pluperfectActive: { name:'Pluperfect',       forms:['issem','issēs','isset','issēmus','issētis','issent'],                endings:['issem','-','-','-','-','-'] },
    },
    imperative: { active: { singular:'ī', plural:'īte' } },
    infinitives: [
      { label:'Present', form:'īre' },
      { label:'Perfect', form:'isse (iisse)' },
      { label:'Future',  form:'itūrum esse' },
    ],
    participles: [
      { label:'Present Active',  form:'iēns, euntis' },
      { label:'Future Active',   form:'itūrus, -a, -um' },
      { label:'Gerundive',       form:'eundum (impers.)' },
    ],
    gerund: { gen:'eundī', dat:'eundō', acc:'eundum', abl:'eundō' },
  },

  ferre: {
    name: 'Irregular: ferre (to carry)',
    lemma: 'ferō, ferre, tulī, lātum',
    meaning: 'to carry, bear, endure',
    indicative: {
      presentActive:     { name:'Present Active',  forms:['ferō','fers','fert','ferimus','fertis','ferunt'],                     endings:['ferō','fers','fert','ferimus','fertis','ferunt'] },
      imperfectActive:   { name:'Imperfect Active',forms:['ferēbam','ferēbās','ferēbat','ferēbāmus','ferēbātis','ferēbant'],    endings:['ferēbam','-','-','-','-','-'] },
      futureActive:      { name:'Future Active',   forms:['feram','ferēs','feret','ferēmus','ferētis','ferent'],                endings:['feram','-','-','-','-','-'] },
      perfectActive:     { name:'Perfect Active',  forms:['tulī','tulistī','tulit','tulimus','tulistis','tulērunt'],            endings:['tulī','-','-','-','-','-'] },
      pluperfectActive:  { name:'Pluperfect Active',forms:['tuleram','tulerās','tulerat','tulerāmus','tulerātis','tulerant'],   endings:['tuleram','-','-','-','-','-'] },
      futperfActive:     { name:'Fut. Perf. Active',forms:['tulerō','tuleris','tulerit','tulerimus','tuleritis','tulerint'],   endings:['tulerō','-','-','-','-','-'] },
      presentPassive:    { name:'Present Passive',  forms:['feror','ferris','fertur','ferimur','feriminī','feruntur'],          endings:['feror','ferris','fertur','ferimur','feriminī','feruntur'] },
      imperfectPassive:  { name:'Imperfect Passive',forms:['ferēbar','ferēbāris','ferēbātur','ferēbāmur','ferēbāminī','ferēbantur'], endings:['ferēbar','-','-','-','-','-'] },
      futurePassive:     { name:'Future Passive',  forms:['ferar','ferēris','ferētur','ferēmur','ferēminī','ferentur'],        endings:['ferar','-','-','-','-','-'] },
      perfectPassive:    { name:'Perfect Passive',  forms:['lātus sum','lātus es','lātus est','lātī sumus','lātī estis','lātī sunt'], endings:['PPP + sum','-','-','-','-','-'] },
      pluperfectPassive: { name:'Pluperfect Passive',forms:['lātus eram','lātus erās','lātus erat','lātī erāmus','lātī erātis','lātī erant'], endings:['PPP + eram','-','-','-','-','-'] },
      futperfPassive:    { name:'Fut. Perf. Passive',forms:['lātus erō','lātus eris','lātus erit','lātī erimus','lātī eritis','lātī erunt'], endings:['PPP + erō','-','-','-','-','-'] },
    },
    subjunctive: {
      presentActive:    { name:'Present Active',   forms:['feram','ferās','ferat','ferāmus','ferātis','ferant'],               endings:['feram','-','-','-','-','-'] },
      imperfectActive:  { name:'Imperfect Active', forms:['ferrem','ferrēs','ferret','ferrēmus','ferrētis','ferrent'],         endings:['ferrem','-','-','-','-','-'] },
      perfectActive:    { name:'Perfect Active',   forms:['tulerim','tulerīs','tulerit','tulerīmus','tulerītis','tulerint'],  endings:['tulerim','-','-','-','-','-'] },
      pluperfectActive: { name:'Pluperfect Active',forms:['tulissem','tulissēs','tulisset','tulissēmus','tulissētis','tulissent'], endings:['tulissem','-','-','-','-','-'] },
      presentPassive:   { name:'Present Passive',  forms:['ferar','ferāris','ferātur','ferāmur','ferāminī','ferantur'],       endings:['ferar','-','-','-','-','-'] },
      imperfectPassive: { name:'Imperfect Passive',forms:['ferrer','ferrēris','ferrētur','ferrēmur','ferrēminī','ferrentur'], endings:['ferrer','-','-','-','-','-'] },
    },
    imperative: {
      active:  { singular:'fer', plural:'ferte', note:'Short form (no final -e)' },
      passive: { singular:'ferre', plural:'feriminī' },
    },
    infinitives: [
      { label:'Present Active',   form:'ferre' },
      { label:'Perfect Active',   form:'tulisse' },
      { label:'Future Active',    form:'lātūrum esse' },
      { label:'Present Passive',  form:'ferrī' },
      { label:'Perfect Passive',  form:'lātum esse' },
      { label:'Future Passive',   form:'lātum īrī' },
    ],
    participles: [
      { label:'Present Active',  form:'ferēns, ferentis' },
      { label:'Perfect Passive', form:'lātus, -a, -um' },
      { label:'Future Active',   form:'lātūrus, -a, -um' },
      { label:'Gerundive',       form:'ferendus, -a, -um' },
    ],
  },

  posse: {
    name: 'Irregular: posse (to be able)',
    lemma: 'possum, posse, potuī',
    meaning: 'to be able, can',
    indicative: {
      presentActive:    { name:'Present',   forms:['possum','potes','potest','possumus','potestis','possunt'],                  endings:['possum','potes','potest','possumus','potestis','possunt'] },
      imperfectActive:  { name:'Imperfect', forms:['poteram','poterās','poterat','poterāmus','poterātis','poterant'],          endings:['poteram','-','-','-','-','-'] },
      futureActive:     { name:'Future',    forms:['poterō','poteris','poterit','poterimus','poteritis','poterunt'],           endings:['poterō','-','-','-','-','-'] },
      perfectActive:    { name:'Perfect',   forms:['potuī','potuistī','potuit','potuimus','potuistis','potuērunt'],            endings:['potuī','-','-','-','-','-'] },
      pluperfectActive: { name:'Pluperfect',forms:['potueram','potuerās','potuerat','potuerāmus','potuerātis','potuerant'],   endings:['potueram','-','-','-','-','-'] },
      futperfActive:    { name:'Fut. Perf.',forms:['potuerō','potueris','potuerit','potuerimus','potueritis','potuerint'],    endings:['potuerō','-','-','-','-','-'] },
    },
    subjunctive: {
      presentActive:    { name:'Present',   forms:['possim','possīs','possit','possīmus','possītis','possint'],               endings:['possim','-','-','-','-','-'] },
      imperfectActive:  { name:'Imperfect', forms:['possem','possēs','posset','possēmus','possētis','possent'],               endings:['possem','-','-','-','-','-'] },
      perfectActive:    { name:'Perfect',   forms:['potuerim','potuerīs','potuerit','potuerīmus','potuerītis','potuerint'],  endings:['potuerim','-','-','-','-','-'] },
      pluperfectActive: { name:'Pluperfect',forms:['potuissem','potuissēs','potuisset','potuissēmus','potuissētis','potuissent'], endings:['potuissem','-','-','-','-','-'] },
    },
    infinitives: [
      { label:'Present', form:'posse' },
      { label:'Perfect', form:'potuisse' },
    ],
    note: 'possum has no passive (intransitive), no imperative, no participles (potēns used as adjective only)',
  },
};

// ─── NOUNS ────────────────────────────────────────────────────────────────────

const NOUN_DATA = {
  first: {
    name: '1st Declension',
    gender: 'Feminine (a few masculine: agricola, nauta, poēta)',
    example: 'puella, puellae',
    meaning: 'girl',
    stem: 'puell-',
    singular: { Nominative:'puella', Genitive:'puellae',  Dative:'puellae',   Accusative:'puellam', Ablative:'puellā',   Vocative:'puella' },
    plural:   { Nominative:'puellae',Genitive:'puellārum',Dative:'puellīs',   Accusative:'puellās', Ablative:'puellīs',  Vocative:'puellae' },
    endings: {
      singular: { Nominative:'-a',   Genitive:'-ae',  Dative:'-ae',   Accusative:'-am',  Ablative:'-ā',    Vocative:'-a' },
      plural:   { Nominative:'-ae',  Genitive:'-ārum',Dative:'-īs',   Accusative:'-ās',  Ablative:'-īs',   Vocative:'-ae' },
    },
  },
  secondM: {
    name: '2nd Declension (Masculine)',
    gender: 'Masculine',
    example: 'servus, servī',
    meaning: 'slave',
    stem: 'serv-',
    singular: { Nominative:'servus', Genitive:'servī',   Dative:'servō',  Accusative:'servum', Ablative:'servō',  Vocative:'serve' },
    plural:   { Nominative:'servī',  Genitive:'servōrum',Dative:'servīs', Accusative:'servōs', Ablative:'servīs', Vocative:'servī' },
    endings: {
      singular: { Nominative:'-us',  Genitive:'-ī',    Dative:'-ō',   Accusative:'-um',  Ablative:'-ō',   Vocative:'-e' },
      plural:   { Nominative:'-ī',   Genitive:'-ōrum', Dative:'-īs',  Accusative:'-ōs',  Ablative:'-īs',  Vocative:'-ī' },
    },
    notes: 'Nouns in -ius have voc. sg. -ī (e.g., fīlī). puer, puerī keeps -e- throughout.',
  },
  secondN: {
    name: '2nd Declension (Neuter)',
    gender: 'Neuter',
    example: 'bellum, bellī',
    meaning: 'war',
    stem: 'bell-',
    singular: { Nominative:'bellum', Genitive:'bellī',   Dative:'bellō',  Accusative:'bellum', Ablative:'bellō',  Vocative:'bellum' },
    plural:   { Nominative:'bella',  Genitive:'bellōrum',Dative:'bellīs', Accusative:'bella',  Ablative:'bellīs', Vocative:'bella' },
    endings: {
      singular: { Nominative:'-um',  Genitive:'-ī',    Dative:'-ō',   Accusative:'-um',  Ablative:'-ō',   Vocative:'-um' },
      plural:   { Nominative:'-a',   Genitive:'-ōrum', Dative:'-īs',  Accusative:'-a',   Ablative:'-īs',  Vocative:'-a' },
    },
    notes: 'Neuter rule: nom., acc., voc. are always identical.',
  },
  thirdCons: {
    name: '3rd Declension (Consonant Stem)',
    gender: 'Masculine / Feminine',
    example: 'rēx, rēgis',
    meaning: 'king',
    stem: 'rēg-',
    singular: { Nominative:'rēx',   Genitive:'rēgis',  Dative:'rēgī',   Accusative:'rēgem', Ablative:'rēge',   Vocative:'rēx' },
    plural:   { Nominative:'rēgēs', Genitive:'rēgum',  Dative:'rēgibus',Accusative:'rēgēs', Ablative:'rēgibus',Vocative:'rēgēs' },
    endings: {
      singular: { Nominative:'—',   Genitive:'-is',   Dative:'-ī',    Accusative:'-em',  Ablative:'-e',    Vocative:'—' },
      plural:   { Nominative:'-ēs', Genitive:'-um',   Dative:'-ibus', Accusative:'-ēs',  Ablative:'-ibus', Vocative:'-ēs' },
    },
    notes: 'Nom. sg. varies; find stem from gen. sg. by removing -is.',
  },
  thirdIsteM: {
    name: '3rd Declension i-stem (M/F)',
    gender: 'Masculine / Feminine',
    example: 'cīvis, cīvis',
    meaning: 'citizen',
    stem: 'cīv-',
    singular: { Nominative:'cīvis', Genitive:'cīvis',   Dative:'cīvī',   Accusative:'cīvem', Ablative:'cīve',   Vocative:'cīvis' },
    plural:   { Nominative:'cīvēs', Genitive:'cīvium',  Dative:'cīvibus',Accusative:'cīvēs', Ablative:'cīvibus',Vocative:'cīvēs' },
    endings: {
      singular: { Nominative:'-is',  Genitive:'-is',   Dative:'-ī',    Accusative:'-em',  Ablative:'-e (-ī)', Vocative:'-is' },
      plural:   { Nominative:'-ēs',  Genitive:'-ium',  Dative:'-ibus', Accusative:'-ēs (-īs)', Ablative:'-ibus', Vocative:'-ēs' },
    },
    notes: 'Key difference from consonant stem: gen. pl. -ium (not -um).',
  },
  thirdIsteN: {
    name: '3rd Declension i-stem (Neuter)',
    gender: 'Neuter',
    example: 'mare, maris',
    meaning: 'sea',
    stem: 'mar-',
    singular: { Nominative:'mare',  Genitive:'maris',  Dative:'marī',   Accusative:'mare',  Ablative:'marī',   Vocative:'mare' },
    plural:   { Nominative:'maria', Genitive:'marium', Dative:'maribus',Accusative:'maria', Ablative:'maribus',Vocative:'maria' },
    endings: {
      singular: { Nominative:'-e',   Genitive:'-is',   Dative:'-ī',    Accusative:'-e',   Ablative:'-ī',    Vocative:'-e' },
      plural:   { Nominative:'-ia',  Genitive:'-ium',  Dative:'-ibus', Accusative:'-ia',  Ablative:'-ibus', Vocative:'-ia' },
    },
    notes: 'Nom./acc. sg. -e; abl. sg. -ī; nom./acc. pl. -ia; gen. pl. -ium.',
  },
  thirdNeutCons: {
    name: '3rd Declension (Neuter Consonant)',
    gender: 'Neuter',
    example: 'opus, operis',
    meaning: 'work, deed',
    stem: 'oper-',
    singular: { Nominative:'opus',  Genitive:'operis', Dative:'operī',  Accusative:'opus',  Ablative:'opere',  Vocative:'opus' },
    plural:   { Nominative:'opera', Genitive:'operum', Dative:'operibus',Accusative:'opera', Ablative:'operibus',Vocative:'opera' },
    endings: {
      singular: { Nominative:'—',   Genitive:'-is',   Dative:'-ī',    Accusative:'—',    Ablative:'-e',    Vocative:'—' },
      plural:   { Nominative:'-a',  Genitive:'-um',   Dative:'-ibus', Accusative:'-a',   Ablative:'-ibus', Vocative:'-a' },
    },
  },
  fourthM: {
    name: '4th Declension (Masculine)',
    gender: 'Masculine',
    example: 'manus, manūs',
    meaning: 'hand; band (of men)',
    stem: 'man-',
    singular: { Nominative:'manus', Genitive:'manūs',  Dative:'manuī',  Accusative:'manum', Ablative:'manū',   Vocative:'manus' },
    plural:   { Nominative:'manūs', Genitive:'manuum', Dative:'manibus',Accusative:'manūs', Ablative:'manibus',Vocative:'manūs' },
    endings: {
      singular: { Nominative:'-us',  Genitive:'-ūs',  Dative:'-uī',   Accusative:'-um',  Ablative:'-ū',    Vocative:'-us' },
      plural:   { Nominative:'-ūs',  Genitive:'-uum', Dative:'-ibus', Accusative:'-ūs',  Ablative:'-ibus', Vocative:'-ūs' },
    },
  },
  fourthN: {
    name: '4th Declension (Neuter)',
    gender: 'Neuter',
    example: 'cornū, cornūs',
    meaning: 'horn',
    stem: 'corn-',
    singular: { Nominative:'cornū',  Genitive:'cornūs', Dative:'cornū',  Accusative:'cornū',  Ablative:'cornū',  Vocative:'cornū' },
    plural:   { Nominative:'cornua', Genitive:'cornuum',Dative:'cornibus',Accusative:'cornua', Ablative:'cornibus',Vocative:'cornua' },
    endings: {
      singular: { Nominative:'-ū',   Genitive:'-ūs',  Dative:'-ū',    Accusative:'-ū',   Ablative:'-ū',    Vocative:'-ū' },
      plural:   { Nominative:'-ua',  Genitive:'-uum', Dative:'-ibus', Accusative:'-ua',  Ablative:'-ibus', Vocative:'-ua' },
    },
  },
  fifth: {
    name: '5th Declension',
    gender: 'Feminine (diēs can be masc.)',
    example: 'rēs, reī',
    meaning: 'thing, matter, affair',
    stem: 'r-',
    singular: { Nominative:'rēs',  Genitive:'reī',  Dative:'reī',  Accusative:'rem', Ablative:'rē',   Vocative:'rēs' },
    plural:   { Nominative:'rēs',  Genitive:'rērum',Dative:'rēbus',Accusative:'rēs', Ablative:'rēbus',Vocative:'rēs' },
    endings: {
      singular: { Nominative:'-ēs', Genitive:'-eī',  Dative:'-eī',  Accusative:'-em', Ablative:'-ē',   Vocative:'-ēs' },
      plural:   { Nominative:'-ēs', Genitive:'-ērum',Dative:'-ēbus',Accusative:'-ēs', Ablative:'-ēbus',Vocative:'-ēs' },
    },
    notes: 'diēs (day) is masculine and also follows this pattern.',
  },
};

// ─── ADJECTIVES ───────────────────────────────────────────────────────────────

const ADJ_DATA = {
  '212': {
    name: '1st/2nd Declension (2-1-2)',
    example: 'bonus, bona, bonum',
    meaning: 'good',
    masculine: {
      singular: { Nominative:'bonus', Genitive:'bonī',   Dative:'bonō',  Accusative:'bonum', Ablative:'bonō',  Vocative:'bone' },
      plural:   { Nominative:'bonī',  Genitive:'bonōrum',Dative:'bonīs', Accusative:'bonōs', Ablative:'bonīs', Vocative:'bonī' },
    },
    feminine: {
      singular: { Nominative:'bona',  Genitive:'bonae',  Dative:'bonae', Accusative:'bonam', Ablative:'bonā',  Vocative:'bona' },
      plural:   { Nominative:'bonae', Genitive:'bonārum',Dative:'bonīs', Accusative:'bonās', Ablative:'bonīs', Vocative:'bonae' },
    },
    neuter: {
      singular: { Nominative:'bonum', Genitive:'bonī',   Dative:'bonō',  Accusative:'bonum', Ablative:'bonō',  Vocative:'bonum' },
      plural:   { Nominative:'bona',  Genitive:'bonōrum',Dative:'bonīs', Accusative:'bona',  Ablative:'bonīs', Vocative:'bona' },
    },
    note: 'Masc. follows 2nd decl. (-us), Fem. follows 1st decl. (-a), Neut. follows 2nd decl. (-um).',
  },
  '3-3': {
    name: '3rd Declension, 3 Endings',
    example: 'ācer, ācris, ācre',
    meaning: 'keen, sharp, fierce',
    masculine: {
      singular: { Nominative:'ācer',  Genitive:'ācris',  Dative:'ācrī',  Accusative:'ācrem', Ablative:'ācrī',  Vocative:'ācer' },
      plural:   { Nominative:'ācrēs', Genitive:'ācrium', Dative:'ācribus',Accusative:'ācrēs',Ablative:'ācribus',Vocative:'ācrēs' },
    },
    feminine: {
      singular: { Nominative:'ācris', Genitive:'ācris',  Dative:'ācrī',  Accusative:'ācrem', Ablative:'ācrī',  Vocative:'ācris' },
      plural:   { Nominative:'ācrēs', Genitive:'ācrium', Dative:'ācribus',Accusative:'ācrēs',Ablative:'ācribus',Vocative:'ācrēs' },
    },
    neuter: {
      singular: { Nominative:'ācre',  Genitive:'ācris',  Dative:'ācrī',  Accusative:'ācre',  Ablative:'ācrī',  Vocative:'ācre' },
      plural:   { Nominative:'ācria', Genitive:'ācrium', Dative:'ācribus',Accusative:'ācria', Ablative:'ācribus',Vocative:'ācria' },
    },
    note: 'Three different nom. sg. forms (m/f/n). Gen. pl. -ium; abl. sg. -ī.',
  },
  '3-2': {
    name: '3rd Declension, 2 Endings',
    example: 'gravis, grave',
    meaning: 'heavy, serious, grave',
    masculine: {
      singular: { Nominative:'gravis', Genitive:'gravis', Dative:'gravī',  Accusative:'gravem', Ablative:'gravī',  Vocative:'gravis' },
      plural:   { Nominative:'gravēs', Genitive:'gravium',Dative:'gravibus',Accusative:'gravēs',Ablative:'gravibus',Vocative:'gravēs' },
    },
    feminine: {
      singular: { Nominative:'gravis', Genitive:'gravis', Dative:'gravī',  Accusative:'gravem', Ablative:'gravī',  Vocative:'gravis' },
      plural:   { Nominative:'gravēs', Genitive:'gravium',Dative:'gravibus',Accusative:'gravēs',Ablative:'gravibus',Vocative:'gravēs' },
    },
    neuter: {
      singular: { Nominative:'grave',  Genitive:'gravis', Dative:'gravī',  Accusative:'grave',  Ablative:'gravī',  Vocative:'grave' },
      plural:   { Nominative:'gravia', Genitive:'gravium',Dative:'gravibus',Accusative:'gravia', Ablative:'gravibus',Vocative:'gravia' },
    },
    note: 'Masc. and fem. share the same forms; neuter differs in nom./acc.',
  },
  '3-1': {
    name: '3rd Declension, 1 Ending',
    example: 'ingēns, ingentis',
    meaning: 'huge, vast',
    masculine: {
      singular: { Nominative:'ingēns',   Genitive:'ingentis', Dative:'ingentī',  Accusative:'ingentem', Ablative:'ingentī',  Vocative:'ingēns' },
      plural:   { Nominative:'ingentēs', Genitive:'ingentium',Dative:'ingentibus',Accusative:'ingentēs',Ablative:'ingentibus',Vocative:'ingentēs' },
    },
    feminine: {
      singular: { Nominative:'ingēns',   Genitive:'ingentis', Dative:'ingentī',  Accusative:'ingentem', Ablative:'ingentī',  Vocative:'ingēns' },
      plural:   { Nominative:'ingentēs', Genitive:'ingentium',Dative:'ingentibus',Accusative:'ingentēs',Ablative:'ingentibus',Vocative:'ingentēs' },
    },
    neuter: {
      singular: { Nominative:'ingēns',   Genitive:'ingentis', Dative:'ingentī',  Accusative:'ingēns',   Ablative:'ingentī',  Vocative:'ingēns' },
      plural:   { Nominative:'ingentia', Genitive:'ingentium',Dative:'ingentibus',Accusative:'ingentia', Ablative:'ingentibus',Vocative:'ingentia' },
    },
    note: 'One nom. sg. form for all genders. Often present participles used as adjectives (e.g., amāns, amantis).',
  },
  'comp': {
    name: 'Comparative Adjective',
    example: 'altior, altius (comp. of altus)',
    meaning: 'taller, higher',
    masculine: {
      singular: { Nominative:'altior',   Genitive:'altiōris', Dative:'altiōrī',  Accusative:'altiōrem', Ablative:'altiōre',  Vocative:'altior' },
      plural:   { Nominative:'altiōrēs', Genitive:'altiōrum', Dative:'altiōribus',Accusative:'altiōrēs',Ablative:'altiōribus',Vocative:'altiōrēs' },
    },
    feminine: {
      singular: { Nominative:'altior',   Genitive:'altiōris', Dative:'altiōrī',  Accusative:'altiōrem', Ablative:'altiōre',  Vocative:'altior' },
      plural:   { Nominative:'altiōrēs', Genitive:'altiōrum', Dative:'altiōribus',Accusative:'altiōrēs',Ablative:'altiōribus',Vocative:'altiōrēs' },
    },
    neuter: {
      singular: { Nominative:'altius',   Genitive:'altiōris', Dative:'altiōrī',  Accusative:'altius',   Ablative:'altiōre',  Vocative:'altius' },
      plural:   { Nominative:'altiōra',  Genitive:'altiōrum', Dative:'altiōribus',Accusative:'altiōra',  Ablative:'altiōribus',Vocative:'altiōra' },
    },
    note: 'Comparatives follow 3rd decl. consonant stem. Formed: stem + -ior (m/f) / -ius (n).',
  },
  'super': {
    name: 'Superlative Adjective',
    example: 'altissimus, altissima, altissimum',
    meaning: 'tallest, very high',
    masculine: {
      singular: { Nominative:'altissimus', Genitive:'altissimī',  Dative:'altissimō', Accusative:'altissimum', Ablative:'altissimō', Vocative:'altissime' },
      plural:   { Nominative:'altissimī',  Genitive:'altissimōrum',Dative:'altissimīs',Accusative:'altissimōs', Ablative:'altissimīs',Vocative:'altissimī' },
    },
    feminine: {
      singular: { Nominative:'altissima',  Genitive:'altissimae', Dative:'altissimae',Accusative:'altissimam', Ablative:'altissimā', Vocative:'altissima' },
      plural:   { Nominative:'altissimae', Genitive:'altissimārum',Dative:'altissimīs',Accusative:'altissimās', Ablative:'altissimīs',Vocative:'altissimae' },
    },
    neuter: {
      singular: { Nominative:'altissimum', Genitive:'altissimī',  Dative:'altissimō', Accusative:'altissimum', Ablative:'altissimō', Vocative:'altissimum' },
      plural:   { Nominative:'altissima',  Genitive:'altissimōrum',Dative:'altissimīs',Accusative:'altissima',  Ablative:'altissimīs',Vocative:'altissima' },
    },
    note: 'Superlatives follow 1st/2nd declension. Formed: stem + -issimus/-a/-um.',
  },
};

// ─── VOCABULARY ───────────────────────────────────────────────────────────────

const VOCAB_DATA = [
  // Nouns – 1st Declension
  { latin:'aqua, aquae', category:'nouns', gender:'f.', meaning:'water', declension:'1st' },
  { latin:'causa, causae', category:'nouns', gender:'f.', meaning:'cause, reason, case', declension:'1st' },
  { latin:'fēmina, fēminae', category:'nouns', gender:'f.', meaning:'woman', declension:'1st' },
  { latin:'fīlia, fīliae', category:'nouns', gender:'f.', meaning:'daughter', declension:'1st' },
  { latin:'fortūna, fortūnae', category:'nouns', gender:'f.', meaning:'fortune, luck, fate', declension:'1st' },
  { latin:'glōria, glōriae', category:'nouns', gender:'f.', meaning:'glory, fame', declension:'1st' },
  { latin:'patria, patriae', category:'nouns', gender:'f.', meaning:'fatherland, homeland', declension:'1st' },
  { latin:'puella, puellae', category:'nouns', gender:'f.', meaning:'girl', declension:'1st' },
  { latin:'terra, terrae', category:'nouns', gender:'f.', meaning:'earth, land, ground', declension:'1st' },
  { latin:'via, viae', category:'nouns', gender:'f.', meaning:'road, way, journey', declension:'1st' },
  { latin:'vīta, vītae', category:'nouns', gender:'f.', meaning:'life', declension:'1st' },
  { latin:'porta, portae', category:'nouns', gender:'f.', meaning:'gate, door', declension:'1st' },
  { latin:'silva, silvae', category:'nouns', gender:'f.', meaning:'forest, wood', declension:'1st' },
  // Nouns – 2nd Declension
  { latin:'amīcus, amīcī', category:'nouns', gender:'m.', meaning:'friend', declension:'2nd' },
  { latin:'animus, animī', category:'nouns', gender:'m.', meaning:'mind, spirit, courage', declension:'2nd' },
  { latin:'bellum, bellī', category:'nouns', gender:'n.', meaning:'war', declension:'2nd' },
  { latin:'caelum, caelī', category:'nouns', gender:'n.', meaning:'sky, heaven', declension:'2nd' },
  { latin:'deus, deī', category:'nouns', gender:'m.', meaning:'god', declension:'2nd' },
  { latin:'dominus, dominī', category:'nouns', gender:'m.', meaning:'master, lord', declension:'2nd' },
  { latin:'fīlius, fīliī', category:'nouns', gender:'m.', meaning:'son', declension:'2nd' },
  { latin:'gladius, gladiī', category:'nouns', gender:'m.', meaning:'sword', declension:'2nd' },
  { latin:'locus, locī', category:'nouns', gender:'m.', meaning:'place, position', declension:'2nd' },
  { latin:'mundus, mundī', category:'nouns', gender:'m.', meaning:'world', declension:'2nd' },
  { latin:'oculus, oculī', category:'nouns', gender:'m.', meaning:'eye', declension:'2nd' },
  { latin:'populus, populī', category:'nouns', gender:'m.', meaning:'people, nation', declension:'2nd' },
  { latin:'puer, puerī', category:'nouns', gender:'m.', meaning:'boy, child', declension:'2nd' },
  { latin:'servus, servī', category:'nouns', gender:'m.', meaning:'slave', declension:'2nd' },
  { latin:'verbum, verbī', category:'nouns', gender:'n.', meaning:'word', declension:'2nd' },
  { latin:'vir, virī', category:'nouns', gender:'m.', meaning:'man, husband, hero', declension:'2nd' },
  { latin:'donum, donī', category:'nouns', gender:'n.', meaning:'gift', declension:'2nd' },
  { latin:'oppidum, oppidī', category:'nouns', gender:'n.', meaning:'town', declension:'2nd' },
  { latin:'proelium, proeliī', category:'nouns', gender:'n.', meaning:'battle', declension:'2nd' },
  // Nouns – 3rd Declension
  { latin:'amor, amōris', category:'nouns', gender:'m.', meaning:'love', declension:'3rd' },
  { latin:'caput, capitis', category:'nouns', gender:'n.', meaning:'head, chief, capital', declension:'3rd' },
  { latin:'cīvis, cīvis', category:'nouns', gender:'m/f.', meaning:'citizen', declension:'3rd' },
  { latin:'corpus, corporis', category:'nouns', gender:'n.', meaning:'body', declension:'3rd' },
  { latin:'dux, ducis', category:'nouns', gender:'m.', meaning:'leader, general', declension:'3rd' },
  { latin:'flūmen, flūminis', category:'nouns', gender:'n.', meaning:'river', declension:'3rd' },
  { latin:'frāter, frātris', category:'nouns', gender:'m.', meaning:'brother', declension:'3rd' },
  { latin:'homō, hominis', category:'nouns', gender:'m.', meaning:'human being, person', declension:'3rd' },
  { latin:'iter, itineris', category:'nouns', gender:'n.', meaning:'journey, route', declension:'3rd' },
  { latin:'lēx, lēgis', category:'nouns', gender:'f.', meaning:'law', declension:'3rd' },
  { latin:'māter, mātris', category:'nouns', gender:'f.', meaning:'mother', declension:'3rd' },
  { latin:'mīles, mīlitis', category:'nouns', gender:'m.', meaning:'soldier', declension:'3rd' },
  { latin:'mors, mortis', category:'nouns', gender:'f.', meaning:'death', declension:'3rd' },
  { latin:'nōmen, nōminis', category:'nouns', gender:'n.', meaning:'name', declension:'3rd' },
  { latin:'nox, noctis', category:'nouns', gender:'f.', meaning:'night', declension:'3rd' },
  { latin:'opus, operis', category:'nouns', gender:'n.', meaning:'work, deed, need', declension:'3rd' },
  { latin:'pars, partis', category:'nouns', gender:'f.', meaning:'part, direction', declension:'3rd' },
  { latin:'pater, patris', category:'nouns', gender:'m.', meaning:'father', declension:'3rd' },
  { latin:'pāx, pācis', category:'nouns', gender:'f.', meaning:'peace', declension:'3rd' },
  { latin:'rēx, rēgis', category:'nouns', gender:'m.', meaning:'king', declension:'3rd' },
  { latin:'soror, sorōris', category:'nouns', gender:'f.', meaning:'sister', declension:'3rd' },
  { latin:'tempus, temporis', category:'nouns', gender:'n.', meaning:'time, season', declension:'3rd' },
  { latin:'urbs, urbis', category:'nouns', gender:'f.', meaning:'city', declension:'3rd' },
  { latin:'vōx, vōcis', category:'nouns', gender:'f.', meaning:'voice, word', declension:'3rd' },
  { latin:'virtūs, virtūtis', category:'nouns', gender:'f.', meaning:'courage, virtue, excellence', declension:'3rd' },
  { latin:'mare, maris', category:'nouns', gender:'n.', meaning:'sea', declension:'3rd' },
  // Nouns – 4th/5th Declension
  { latin:'exercitus, exercitūs', category:'nouns', gender:'m.', meaning:'army', declension:'4th' },
  { latin:'manus, manūs', category:'nouns', gender:'f.', meaning:'hand; band of men', declension:'4th' },
  { latin:'senātus, senātūs', category:'nouns', gender:'m.', meaning:'senate', declension:'4th' },
  { latin:'diēs, diēī', category:'nouns', gender:'m/f.', meaning:'day', declension:'5th' },
  { latin:'rēs, reī', category:'nouns', gender:'f.', meaning:'thing, matter, affair, reality', declension:'5th' },
  { latin:'spēs, speī', category:'nouns', gender:'f.', meaning:'hope', declension:'5th' },
  // Verbs
  { latin:'amō, amāre, amāvī, amātum', category:'verbs', conj:'1st', meaning:'to love, like' },
  { latin:'laudō, laudāre, laudāvī, laudātum', category:'verbs', conj:'1st', meaning:'to praise' },
  { latin:'nārrō, nārrāre, nārrāvī, nārrātum', category:'verbs', conj:'1st', meaning:'to tell, relate, narrate' },
  { latin:'parō, parāre, parāvī, parātum', category:'verbs', conj:'1st', meaning:'to prepare, get' },
  { latin:'pugnō, pugnāre, pugnāvī, pugnātum', category:'verbs', conj:'1st', meaning:'to fight' },
  { latin:'vocō, vocāre, vocāvī, vocātum', category:'verbs', conj:'1st', meaning:'to call, summon' },
  { latin:'dō, dare, dedī, datum', category:'verbs', conj:'1st (irreg.)', meaning:'to give' },
  { latin:'habeō, habēre, habuī, habitum', category:'verbs', conj:'2nd', meaning:'to have, hold, consider' },
  { latin:'maneō, manēre, mānsī, mānsum', category:'verbs', conj:'2nd', meaning:'to remain, stay, wait' },
  { latin:'moneō, monēre, monuī, monitum', category:'verbs', conj:'2nd', meaning:'to warn, advise, remind' },
  { latin:'moveō, movēre, mōvī, mōtum', category:'verbs', conj:'2nd', meaning:'to move' },
  { latin:'timeō, timēre, timuī', category:'verbs', conj:'2nd', meaning:'to fear, be afraid of' },
  { latin:'videō, vidēre, vīdī, vīsum', category:'verbs', conj:'2nd', meaning:'to see; (pass.) seem' },
  { latin:'dīcō, dīcere, dīxī, dictum', category:'verbs', conj:'3rd', meaning:'to say, speak, tell' },
  { latin:'dūcō, dūcere, dūxī, ductum', category:'verbs', conj:'3rd', meaning:'to lead, guide, consider' },
  { latin:'gerō, gerere, gessī, gestum', category:'verbs', conj:'3rd', meaning:'to carry on, wage, wear' },
  { latin:'legō, legere, lēgī, lectum', category:'verbs', conj:'3rd', meaning:'to read, choose, gather' },
  { latin:'mittō, mittere, mīsī, missum', category:'verbs', conj:'3rd', meaning:'to send, let go' },
  { latin:'petō, petere, petīvī, petītum', category:'verbs', conj:'3rd', meaning:'to seek, head for, attack, beg' },
  { latin:'pōnō, pōnere, posuī, positum', category:'verbs', conj:'3rd', meaning:'to put, place, set up' },
  { latin:'quaerō, quaerere, quaesīvī, quaesītum', category:'verbs', conj:'3rd', meaning:'to seek, ask, inquire' },
  { latin:'regō, regere, rēxī, rectum', category:'verbs', conj:'3rd', meaning:'to rule, guide' },
  { latin:'scrībō, scrībere, scrīpsī, scrīptum', category:'verbs', conj:'3rd', meaning:'to write' },
  { latin:'vincō, vincere, vīcī, victum', category:'verbs', conj:'3rd', meaning:'to conquer, win' },
  { latin:'vivō, vīvere, vīxī, victum', category:'verbs', conj:'3rd', meaning:'to live' },
  { latin:'capiō, capere, cēpī, captum', category:'verbs', conj:'3rd-iō', meaning:'to take, capture, seize' },
  { latin:'faciō, facere, fēcī, factum', category:'verbs', conj:'3rd-iō', meaning:'to do, make, cause' },
  { latin:'fugiō, fugere, fūgī, fugitum', category:'verbs', conj:'3rd-iō', meaning:'to flee, escape, avoid' },
  { latin:'iaciō, iacere, iēcī, iactum', category:'verbs', conj:'3rd-iō', meaning:'to throw, hurl' },
  { latin:'audiō, audīre, audīvī, audītum', category:'verbs', conj:'4th', meaning:'to hear, listen to' },
  { latin:'veniō, venīre, vēnī, ventum', category:'verbs', conj:'4th', meaning:'to come, go' },
  { latin:'sciō, scīre, scīvī, scītum', category:'verbs', conj:'4th', meaning:'to know' },
  { latin:'sum, esse, fuī, futūrum', category:'verbs', conj:'irregular', meaning:'to be, exist' },
  { latin:'possum, posse, potuī', category:'verbs', conj:'irregular', meaning:'to be able, can' },
  { latin:'eō, īre, iī/īvī, itum', category:'verbs', conj:'irregular', meaning:'to go' },
  { latin:'ferō, ferre, tulī, lātum', category:'verbs', conj:'irregular', meaning:'to carry, bear, endure, say' },
  { latin:'volō, velle, voluī', category:'verbs', conj:'irregular', meaning:'to want, wish, be willing' },
  { latin:'nōlō, nōlle, nōluī', category:'verbs', conj:'irregular', meaning:'to not want, be unwilling' },
  { latin:'mālō, mālle, māluī', category:'verbs', conj:'irregular', meaning:'to prefer, want rather' },
  // Adjectives
  { latin:'altus, -a, -um', category:'adjectives', meaning:'high, tall, deep' },
  { latin:'bonus, -a, -um', category:'adjectives', meaning:'good, kind' },
  { latin:'clārus, -a, -um', category:'adjectives', meaning:'clear, bright, famous, illustrious' },
  { latin:'dūrus, -a, -um', category:'adjectives', meaning:'hard, harsh, tough' },
  { latin:'fēlīx, fēlīcis', category:'adjectives', meaning:'lucky, happy, fortunate' },
  { latin:'fortis, forte', category:'adjectives', meaning:'brave, strong, courageous' },
  { latin:'gravis, grave', category:'adjectives', meaning:'heavy, serious, important, severe' },
  { latin:'ingēns, ingentis', category:'adjectives', meaning:'huge, vast, enormous' },
  { latin:'longus, -a, -um', category:'adjectives', meaning:'long' },
  { latin:'magnus, -a, -um', category:'adjectives', meaning:'great, large, important' },
  { latin:'malus, -a, -um', category:'adjectives', meaning:'bad, evil, wicked' },
  { latin:'multus, -a, -um', category:'adjectives', meaning:'much, many' },
  { latin:'novus, -a, -um', category:'adjectives', meaning:'new, strange' },
  { latin:'omnis, omne', category:'adjectives', meaning:'all, every, whole' },
  { latin:'parvus, -a, -um', category:'adjectives', meaning:'small, little' },
  { latin:'pulcher, pulchra, pulchrum', category:'adjectives', meaning:'beautiful, handsome, fine' },
  { latin:'sacer, sacra, sacrum', category:'adjectives', meaning:'sacred, holy' },
  { latin:'summus, -a, -um', category:'adjectives', meaning:'highest, greatest, top of' },
  { latin:'verus, -a, -um', category:'adjectives', meaning:'true, real, genuine' },
  { latin:'liber, lībera, līberum', category:'adjectives', meaning:'free' },
  { latin:'medius, -a, -um', category:'adjectives', meaning:'middle (of)' },
  // Adverbs & Prepositions
  { latin:'ab / ā (+ abl.)', category:'adverbs', meaning:'from, away from, by (agent)' },
  { latin:'ad (+ acc.)', category:'adverbs', meaning:'to, toward, at, near' },
  { latin:'ante (+ acc.)', category:'adverbs', meaning:'before, in front of' },
  { latin:'apud (+ acc.)', category:'adverbs', meaning:'at, near, among, in the works of' },
  { latin:'cum (+ abl.)', category:'adverbs', meaning:'with, together with' },
  { latin:'dē (+ abl.)', category:'adverbs', meaning:'down from, about, concerning' },
  { latin:'ex / ē (+ abl.)', category:'adverbs', meaning:'out of, from' },
  { latin:'in (+ acc.)', category:'adverbs', meaning:'into, onto, against' },
  { latin:'in (+ abl.)', category:'adverbs', meaning:'in, on, among' },
  { latin:'inter (+ acc.)', category:'adverbs', meaning:'between, among' },
  { latin:'per (+ acc.)', category:'adverbs', meaning:'through, by means of, throughout' },
  { latin:'post (+ acc.)', category:'adverbs', meaning:'after, behind' },
  { latin:'prō (+ abl.)', category:'adverbs', meaning:'in front of, on behalf of, for, in place of' },
  { latin:'propter (+ acc.)', category:'adverbs', meaning:'on account of, because of' },
  { latin:'sine (+ abl.)', category:'adverbs', meaning:'without' },
  { latin:'sub (+ abl./acc.)', category:'adverbs', meaning:'under, beneath' },
  { latin:'bene', category:'adverbs', meaning:'well' },
  { latin:'iam', category:'adverbs', meaning:'now, already, soon' },
  { latin:'nōn', category:'adverbs', meaning:'not' },
  { latin:'nunc', category:'adverbs', meaning:'now, at present' },
  { latin:'saepe', category:'adverbs', meaning:'often' },
  { latin:'semper', category:'adverbs', meaning:'always' },
  { latin:'tum / tunc', category:'adverbs', meaning:'then, at that time' },
  { latin:'valdē', category:'adverbs', meaning:'very, greatly, intensely' },
  // Conjunctions & Pronouns
  { latin:'et', category:'conjunctions', meaning:'and' },
  { latin:'et...et', category:'conjunctions', meaning:'both...and' },
  { latin:'aut', category:'conjunctions', meaning:'or' },
  { latin:'aut...aut', category:'conjunctions', meaning:'either...or' },
  { latin:'sed', category:'conjunctions', meaning:'but' },
  { latin:'at / ast', category:'conjunctions', meaning:'but (strong contrast)' },
  { latin:'autem (postpos.)', category:'conjunctions', meaning:'but, moreover, however' },
  { latin:'enim (postpos.)', category:'conjunctions', meaning:'for, indeed, in fact' },
  { latin:'nec / neque', category:'conjunctions', meaning:'and not, nor' },
  { latin:'neque...neque', category:'conjunctions', meaning:'neither...nor' },
  { latin:'nam / namque', category:'conjunctions', meaning:'for, because' },
  { latin:'sī', category:'conjunctions', meaning:'if' },
  { latin:'nisi', category:'conjunctions', meaning:'unless, if not, except' },
  { latin:'quod', category:'conjunctions', meaning:'because, that (conj.)' },
  { latin:'ubi', category:'conjunctions', meaning:'where, when' },
  { latin:'ut (+ subj.)', category:'conjunctions', meaning:'so that, in order that, that' },
  { latin:'ut (+ indic.)', category:'conjunctions', meaning:'as, when, how' },
  { latin:'cum (+ subj.)', category:'conjunctions', meaning:'when, since, although (conj.)' },
  { latin:'igitur (postpos.)', category:'conjunctions', meaning:'therefore, and so' },
  { latin:'ergō', category:'conjunctions', meaning:'therefore, consequently' },
  { latin:'tamen', category:'conjunctions', meaning:'nevertheless, however, yet' },
  { latin:'quamquam', category:'conjunctions', meaning:'although, even though' },
  { latin:'ego, meī', category:'conjunctions', meaning:'I, me (1st pers. sg. pronoun)' },
  { latin:'tū, tuī', category:'conjunctions', meaning:'you, your (2nd pers. sg. pronoun)' },
  { latin:'nōs, nostrī', category:'conjunctions', meaning:'we, us (1st pers. pl. pronoun)' },
  { latin:'vōs, vestrī', category:'conjunctions', meaning:'you, your (2nd pers. pl. pronoun)' },
  { latin:'is, ea, id', category:'conjunctions', meaning:'he, she, it; that; this (demonstrative/3rd pers. pronoun)' },
  { latin:'hic, haec, hoc', category:'conjunctions', meaning:'this (near speaker)' },
  { latin:'ille, illa, illud', category:'conjunctions', meaning:'that, he/she/it (3rd pers. emphasis)' },
  { latin:'ipse, ipsa, ipsum', category:'conjunctions', meaning:'himself, herself, itself; the very' },
  { latin:'idem, eadem, idem', category:'conjunctions', meaning:'the same' },
  { latin:'quī, quae, quod', category:'conjunctions', meaning:'who, which, that (relative pronoun)' },
  { latin:'quis, quid', category:'conjunctions', meaning:'who? what? (interrogative pronoun)' },
];

// ─── SENTENCES ────────────────────────────────────────────────────────────────

const SENTENCE_DATA = [
  { latin:'Vēnī, vīdī, vīcī.', translation:'I came, I saw, I conquered.', source:'Julius Caesar', category:'quotes', notes:'Perfect active indicative, 1st sg.' },
  { latin:'Alea iacta est.', translation:'The die has been cast.', source:'Julius Caesar', category:'quotes', notes:'Perfect passive indicative.' },
  { latin:'Gallia est omnis dīvīsa in partēs trēs.', translation:'Gaul as a whole is divided into three parts.', source:'Caesar, De Bello Gallico I.1', category:'literature', notes:'Famous opening line.' },
  { latin:'Arma virumque canō.', translation:'I sing of arms and the man.', source:'Virgil, Aeneid I.1', category:'literature', notes:'Opening of the Aeneid.' },
  { latin:'Amor vincit omnia.', translation:'Love conquers all.', source:'Virgil, Eclogues X.69', category:'quotes', notes:'omnia = all things (acc. pl. neut.).' },
  { latin:'Fortūna audācēs iuvat.', translation:'Fortune favors the bold.', source:'Virgil, Aeneid X.284', category:'quotes', notes:'audācēs = acc. pl. of audāx.' },
  { latin:'Carpe diem, quam minimum crēdula posterō.', translation:'Seize the day, trusting as little as possible in tomorrow.', source:'Horace, Odes I.11', category:'quotes', notes:'carpe = imperative of carpō; diem = acc.' },
  { latin:'Dum spīrō, spērō.', translation:'While I breathe, I hope.', source:'Cicero / Latin proverb', category:'quotes', notes:'spīrō/spērō = 1st sg. present active.' },
  { latin:'In vīnō vēritās.', translation:'In wine, there is truth.', source:'Pliny the Elder', category:'quotes', notes:'Elliptical; est is implied.' },
  { latin:'Ō tempora, ō mōrēs!', translation:'Oh, the times! Oh, the customs!', source:'Cicero, In Catilinam I.1', category:'quotes', notes:'Exclamatory nominatives.' },
  { latin:'Errāre hūmānum est.', translation:'To err is human.', source:'Seneca', category:'quotes', notes:'errāre = present infinitive as subject.' },
  { latin:'Ars longa, vīta brevis.', translation:'Art (craft) is long; life is short.', source:'Hippocrates / Seneca', category:'quotes', notes:'Elliptical; est implied twice.' },
  { latin:'Per aspera ad astra.', translation:'Through hardships to the stars.', source:'Seneca, Hercules Furens', category:'quotes', notes:'aspera = rough things (neut. pl.).' },
  { latin:'Sīc trānsit glōria mundī.', translation:'Thus passes the glory of the world.', source:'Thomas à Kempis', category:'quotes', notes:'trānsit = 3rd sg. present active.' },
  { latin:'Historia magistra vītae est.', translation:'History is life\'s teacher.', source:'Cicero, De Oratore II.36', category:'quotes', notes:'magistra = teacher (f.); vītae = gen.' },
  { latin:'Nōn scholae sed vītae discimus.', translation:'We learn not for school but for life.', source:'Seneca, Epistulae 106', category:'quotes', notes:'discimus = 1st pl. present; dative of purpose.' },
  { latin:'Hominēs, dum docent, discunt.', translation:'Men learn while they teach.', source:'Seneca', category:'quotes', notes:'dum + present indicative.' },
  { latin:'Imperāre sibī maximum imperium est.', translation:'To rule oneself is the greatest power.', source:'Seneca', category:'quotes', notes:'sibī = reflexive dative.' },
  { latin:'Nē quid nimis.', translation:'Nothing in excess.', source:'Terence', category:'quotes', notes:'Greek aphorism (mēdén ágan) in Latin.' },
  { latin:'Senātus Populusque Rōmānus.', translation:'The Senate and the People of Rome.', source:'SPQR', category:'quotes', notes:'Standard formula of the Roman Republic.' },
  { latin:'Puer in silvam ambulat.', translation:'The boy walks into the forest.', source:'Grammar example', category:'grammar', notes:'puer = nom. sg.; silvam = acc. (motion toward).' },
  { latin:'Puella aquam portat.', translation:'The girl carries water.', source:'Grammar example', category:'grammar', notes:'aquam = acc. sg. (direct object).' },
  { latin:'Mīlitēs fortiter pugnābant.', translation:'The soldiers were fighting bravely.', source:'Grammar example', category:'grammar', notes:'Imperfect active indicative; fortiter = adverb.' },
  { latin:'Rōmānī hostēs vīcērunt.', translation:'The Romans conquered the enemy.', source:'Grammar example', category:'grammar', notes:'vīcērunt = 3rd pl. perfect active.' },
  { latin:'Dux mīlitibus imperāvit ut castra mūnīrent.', translation:'The leader ordered the soldiers to fortify the camp.', source:'Grammar example', category:'grammar', notes:'Indirect command: ut + subjunctive.' },
  { latin:'Sī vīs pācem, parā bellum.', translation:'If you want peace, prepare for war.', source:'Vegetius / proverb', category:'quotes', notes:'Conditional sentence; vīs = irreg. 2nd sg. of volō.' },
  { latin:'Cogitō, ergō sum.', translation:'I think, therefore I am.', source:'Descartes (Latin version)', category:'quotes', notes:'cogitō / sum = 1st sg. present.' },
  { latin:'Mors omnia aequat.', translation:'Death equalizes all things.', source:'Seneca / proverb', category:'quotes', notes:'aequat = 3rd sg. present active.' },
  { latin:'Verba volant, scrīpta manent.', translation:'Spoken words fly away; written words remain.', source:'Latin proverb', category:'quotes', notes:'volant/manent = 3rd pl. present.' },
  { latin:'Ab initio.', translation:'From the beginning.', source:'Legal/academic Latin', category:'quotes', notes:'ab + ablative; common phrase.' },
  { latin:'Caesar Rōmam rediit postquam Galliam vīcit.', translation:'Caesar returned to Rome after he had conquered Gaul.', source:'Grammar example', category:'grammar', notes:'postquam + perfect indicative.' },
  { latin:'Puer quem vīdī fīlius rēgis erat.', translation:'The boy whom I saw was the son of the king.', source:'Grammar example', category:'grammar', notes:'Relative clause; quem = acc. sg. m. of quī.' },
];

// ─── PRONOUN REFERENCE ────────────────────────────────────────────────────────

const PRONOUN_DATA = {
  personal: {
    first: {
      name: 'First Person',
      singular: { Nominative:'ego', Genitive:'meī', Dative:'mihi', Accusative:'mē', Ablative:'mē', Vocative:'—' },
      plural:   { Nominative:'nōs', Genitive:'nostrī/nostrum', Dative:'nōbīs', Accusative:'nōs', Ablative:'nōbīs', Vocative:'—' },
    },
    second: {
      name: 'Second Person',
      singular: { Nominative:'tū', Genitive:'tuī', Dative:'tibi', Accusative:'tē', Ablative:'tē', Vocative:'tū' },
      plural:   { Nominative:'vōs', Genitive:'vestrī/vestrum', Dative:'vōbīs', Accusative:'vōs', Ablative:'vōbīs', Vocative:'vōs' },
    },
    reflexive: {
      name: 'Reflexive (3rd Person)',
      singular: { Nominative:'—', Genitive:'suī', Dative:'sibi', Accusative:'sē', Ablative:'sē', Vocative:'—' },
      plural:   { Nominative:'—', Genitive:'suī', Dative:'sibi', Accusative:'sē', Ablative:'sē', Vocative:'—' },
    },
  },
};
